# Generated by Django 5.0.6 on 2024-05-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Наличными', 'cash'), ('Перевод', 'card')], default='card', max_length=10, verbose_name='Способо оплаты'),
        ),
    ]
